var
	APIDOG_CONST_ACCESS_TOKEN = "access_token",
	APIDOG_CONST_VERSION = "v",
	APIDOG_CONST_LANG = "lang",
	APIDOG_CONST_RANDOM = "random",
	APIDOG_CONST_ACT = "act",
	APIDOG_CONST_OWNER_ID = "ownerId",
	APIDOG_CONST_TARGET = "target",
	APIDOG_CONST_GENRE_ID = "genreId",
	APIDOG_CONST_FOREIGN = "foreign",


	APIDOG_REQUEST_DEFAULT_VERSION = 4.99,

	APIDOG_REQUEST_VIA_DIRECT = 0,
	APIDOG_REQUEST_VIA_PROXY = 1,
	APIDOG_REQUEST_VIA_EXTENSION = 2,

	APIDOG_REQUEST_WRAPPER_V5 = 2,

	APIDOG_REQUEST_ERROR_API = 3,
	APIDOG_REQUEST_ERROR_INTERNAL = 4,

	APIDOG_REQUEST_STATE_CREATED = 0,
	APIDOG_REQUEST_STATE_PREPARED = 1,
	APIDOG_REQUEST_STATE_REQUESTED = 2,
	APIDOG_REQUEST_STATE_LOADED = 3,

	APIDOG_REQUEST_API_ERROR_INVALID_TOKEN = 5,
	APIDOG_REQUEST_API_ERROR_CAPTCHA = 14,
	APIDOG_REQUEST_API_ERROR_RUNTIME = 13,

	APIDOG_REQUEST_FAILED_BY_UNKNOWN = 1,
	APIDOG_REQUEST_FAILED_BY_NETWORK_PROBLEMS = 2,
	APIDOG_REQUEST_FAILED_BY_APIDOG_DOWN = 3,
	APIDOG_REQUEST_FAILED_BY_VK_DOWN = 3,


	APIDOG_TIME_INTERVAL_DAY = 24 * 60 * 60,


	APIDOG_SETTINGS_AUTOREAD = 2,
	APIDOG_SETTINGS_PROXY = 4,
	APIDOG_SETTINGS_LONGPOLL = 8,
	APIDOG_SETTINGS_SEND_TYPING = 2048,
	APIDOG_SETTINGS_SEND_BY_ENTER = 8192,
	APIDOG_SETTINGS_DIALOGS_REVERSE = 32768,


	APIDOG_SHARE_STEP_CHOOSE_TARGET_TYPE = 1,
	APIDOG_SHARE_STEP_CHOOSE_TARGET_ID = 2,
	APIDOG_SHARE_STEP_ADD_COMMENT = 3,
	APIDOG_SHARE_STEP_DO_SHARE = 4,

	APIDOG_SHARE_TARGET_WALL = 0,
	APIDOG_SHARE_TARGET_TYPE_MESSAGE = 1,
	APIDOG_SHARE_TARGET_TYPE_GROUP = 2


	APIDOG_SETTING_ONLY_FRIENDS = 1,
	APIDOG_SETTING_FROM_GROUP = 2,
	APIDOG_SETTING_SIGNED = 4,
	APIDOG_SETTING_EXPORT_TWITTER = 8,
	APIDOG_SETTING_EXPORT_FACEBOOK = 16,

	APIDOG_ATTACHMENT_PHOTO = 1,
	APIDOG_ATTACHMENT_VIDEO = 2,
	APIDOG_ATTACHMENT_AUDIO = 4,
	APIDOG_ATTACHMENT_DOCUMENT = 8,
	APIDOG_ATTACHMENT_MAP = 16,
	APIDOG_ATTACHMENT_POLL = 32,
	APIDOG_ATTACHMENT_LINK = 64,
	APIDOG_ATTACHMENT_NOTE = 128,
	APIDOG_ATTACHMENT_PAGE = 256,
	APIDOG_ATTACHMENT_ALBUM = 512,
	APIDOG_ATTACHMENT_TIMER = 1024,
	APIDOG_ATTACHMENT_STICKER = 2048,


	APIDOG_UI_EW_TYPE_ITEM_SIMPLE = 0,
	APIDOG_UI_EW_TYPE_ITEM_TEXTAREA = 1,
	APIDOG_UI_EW_TYPE_ITEM_SELECT = 2,
	APIDOG_UI_EW_TYPE_ITEM_CHECKBOX = 3,
	APIDOG_UI_EW_TYPE_ITEM_RADIO = 4;
	APIDOG_UI_EW_TYPE_ITEM_CUSTOM = 5,

	/* Mail.js */
	APIDOG_DIALOG_PEER_USER = "u",
	APIDOG_DIALOG_PEER_CHAT = "c",
	APIDOG_DIALOG_PEER_GROUP = "g",
	APIDOG_DIALOG_PEER_CHAT_MAX_ID = 2000000000,

	STICKERS_SCHEMA_THUMBNAIL = "\/\/vk.com\/images\/store\/stickers\/%c\/thumb_22.png",
	STICKERS_SCHEMA_IMAGE = "\/\/vk.com\/images\/stickers\/%s/128b.png",
	STICKERS_SCHEMA_BACKGROUND = "\/\/vk.com\/images\/store\/stickers\/%s\/background.png";

